#pragma once

enum eTriggerState : unsigned int
{
    TRIGGER_STATE_DEFAULT = 0,
    TRIGGER_STATE_DISABLED = TRIGGER_STATE_DEFAULT,
    TRIGGER_STATE_ALWAYS = 1,
    TRIGGER_STATE_ENABLED = TRIGGER_STATE_ALWAYS,
    TRIGGER_STATE_NEVER = 2,
    AMOUNT_OF_TRIGGER_STATES
};
enum ePhoenixResurrectionState : unsigned int
{
    RESURRECTION_STATE_DEFAULT = 0,
    RESURRECTION_STATE_0_FROM_ANY = 1,
    RESURRECTION_STATE_1_FROM_ANY = 2,
    RESURRECTION_STATE_2_FROM_2 = 3,
    RESURRECTION_STATE_3_FROM_3_OR_4 = 4,
    RESURRECTION_STATE_4_FROM_4 = 5,
    AMOUNT_OF_RESURRECTION_STATES
};
enum eSideAbility
{
    SIDE_SETTING_NONE = -1,
    SIDE_SETTING_UNAFFECTED_BY_MORALE,
    SIDE_SETTING_UNAFFECTED_BY_LUCK,
    SIDE_SETTING_UNAFFECTED_BY_FEAR, // target setting supresses side setting
    SIDE_SETTING_UNAFFECTED_BY_RESISTANCE,
    AMOUNT_OF_SIDE_SETTINGS
};

enum eStackAbility
{
    STACK_SETTING_NONE = -1,
    STACK_SETTING_POSITIVE_MORALE,
    STACK_SETTING_NEGATIVE_MORALE,
    STACK_SETTING_FEAR,
    STACK_SETTING_SPELL_CASTING,
    STACK_SETTING_PHOENIX_RESURRECTION, // AMOUNT_OF_RESURRECTION_STATES
    STACK_SETTING_MAGIC_RESISTANCE,
    STACK_SETTING_MAGIC_MIRROR,
    STACK_SETTING_POSITIVE_LUCK,
    STACK_SETTING_DOUBLE_LUCK,
    STACK_SETTING_DOUBLE_DAMAGE,
    STACK_SETTING_WALL_ATTACK_AIM, // 2
    STACK_SETTING_AFTER_ATTACK_ABILITY,
    STACK_SETTING_DAMAGE_VARIATION_FIRST,
    STACK_SETTING_DAMAGE_VARIATION_SECOND,
    STACK_SETTING_DAMAGE_INPUT, // 2 ( for the wall attack 
    AMOUNT_OF_STACK_SETTINGS
};
enum eAbilityStateSwitchError : UINT
{
    ABILITY_SWITCH_SUCCESS = 0,
    ABILITY_SWITCH_NO_ATTEMPTS_LEFT,
    ABILITY_SWITCH_SWITCH_BLOCKED,
    ABILITY_SWITCH_NO_EFFECT,
    ABILITY_SWITCH_NO_ABILITY,
};

struct Ability
{
    union {
        eTriggerState triggerState;
        ePhoenixResurrectionState resurrectionState = RESURRECTION_STATE_DEFAULT;
    };
    union {
        INT8 duration;
        eSpell spellToCast = eSpell::NONE;
    };
    UINT8 cost = 0;
    bool isTriggered = false;

    inline void DecreaseTriggeredDuration()
    {
        if (isTriggered && --duration <= 0)
            *this = {};
    }
};
